### ISSUE TITLE
libcurl3/libcurl4 mismatch issue (version `CURL_OPENSSL_3' not found)

### ISSUE THREAD

**Issue by shiftkey** [desktop/dugite-native#109]
Looks like there's some more work from #102 around managing `libcurl.so.4` because of how the Ubuntu toolchain works:

 - Trusty installs `libcurl3` which does contain `libcurl.so.4` but this also contains `CURL_OPENSSL_3`
 - https://github.com/curl/curl/issues/2433 indicates this is not done by the curl maintainers, but by the distro maintainers themselves
 - other users on newer Ubuntu distros or Arch have noticed this error because their version of `libcurl.so.4` does not contain this

**Comment by immackay** [comment]
A current fix on Arch is to install [libcurl-openssl-1.0](https://aur.archlinux.org/packages/libcurl-openssl-1.0/) from the AUR and then preload that library, eg:

 ```printf "#!/bin/sh\n\nLD_PRELOAD=/usr/lib/libcurl-openssl-1.0.so /opt/github-desktop/desktop \"\$@\"\n" | install -Dm755 /dev/stdin /usr/bin/github-desktop```

I'm sure that something similar could be performed on other distros if needed.

**Comment by shiftkey** [comment]
I believe this has been resolved with `v.2.19.1-3` which is available on NPM with `dugite` `1.79.0`, but it's not going to make it into GitHub Desktop until next week or so.
