### ISSUE TITLE
add steps to updating submodules instructions

### ISSUE THREAD

**Issue by outofambit** [desktop/dugite-native#119]
specify `git push origin` before `git push origin --tags` in making changes doc

**Comment by shiftkey** [comment]
Or just [`git push --follow-tags`](https://git-scm.com/docs/git-push#git-push---follow-tags) that will do both at once:

> Push all the refs that would be pushed without this option, and also push annotated tags in `refs/tags` that are missing from the remote but are pointing at commit-ish that are reachable from the refs being pushed. 

This is what we currently do after [publishing `dugite` to NPM](https://github.com/desktop/dugite/blob/master/package.json#L11), so doing the same here makes sense:

```
"postpublish": "git push --follow-tags",
```

**Comment by shiftkey** [comment]
Fixed in 67ab4d4
