### ISSUE TITLE
Add option to exclude git-lfs

### ISSUE THREAD

**Issue by hbons** [desktop/dugite-native#120]
I'm using `build-ubuntu.sh` to create a git install for bundling. It looks like recently there were some changes made to the build script to error out when git-lfs could not be downloaded. Since I'm building as a [flatpak](https://flatpak.org), there's no network available to keep the build reproducible and the build of my app will fail.

It would be great if there was an option to exclude git-lfs from the build for this use case. (I do require git-lfs for my app, but I'm fetching that manually)

**Comment by shiftkey** [comment]
@hbons is there a reason why you can't use the [release builds](https://github.com/desktop/dugite-native/releases)?

**Comment by hbons** [comment]
Reading the script I realised there's another reason my build failed aside from the network being unavailable: I didn't set any of the GIT_LFS_* env variables. Maybe the git-lfs bundling can be skipped if `GIT_LFS_VERSION` isn't set? It probably should warn if any of these variables are empty too to prevent user errors.

Would you accept such a change? I can create a PR.

**Comment by shiftkey** [comment]
> Would you accept such a change? I can create a PR.

This seems reasonable. If you can include some sort of tracing message to indicate that "Git LFS bundling has been skipped because GIT_LFS_VERSION has been excluded" then that's fine.

I can follow up later to verify if we need to add any checks for `GIT_LFS_CHECKSUM`.
