### ISSUE TITLE
Not compatible with GLIBC 2.27

### ISSUE THREAD

**Issue by OsoTranquilo** [desktop/dugite-native#133]
Ubuntu upgraded to version 18.04.1 breaks applications

Here is the error message from Atom:

/snap/atom/199/usr/share/atom/resources/app.asar.unpacked/node_modules/dugite/git/libexec/git-core/git-remote-https: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /usr/lib/x86_64-linux-gnu/libgnutls.so.30)

/snap/atom/199/usr/share/atom/resources/app.asar.unpacked/node_modules/dugite/git/libexec/git-core/git-remote-https: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.26' not found (required by /usr/lib/x86_64-linux-gnu/libp11-kit.so.0)

**Comment by shiftkey** [comment]
@OsoTranquilo thanks for the report. I'm building `dugite-native` against a relatively old version of GLIBC, and as a sanity check I added some tracing in #121 to log the symbols that the generated binaries needs as part of the build output:

e.g. https://travis-ci.org/desktop/dugite-native/jobs/441815933#L1291

```
File: ./libexec/git-core/git-remote-http
readelf output:
 0x0000000000000001 (NEEDED)             Shared library: [libcurl.so.4]
 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [librt.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
objdump output:
GLIBC_2.14 
GLIBC_2.2.5
GLIBC_2.3 
GLIBC_2.3.4
GLIBC_2.4 
```

Please follow along with the downstream Atom discussion about this feature, as I believe something in the packaging is involved beyond what I'm currently generating here:  https://github.com/atom/atom/issues/18170
