### ISSUE TITLE
investigate speeding up ARM64 builds

### ISSUE THREAD

**Issue by shiftkey** [desktop/dugite-native#139]

**Comment by outofambit** [comment]
superseded by #315

**Comment by RussianNeuroMancer** [comment]
@shiftkey @outofambit no chances for using more performant hardware?

**Comment by outofambit** [comment]
@RussianNeuroMancer we're not currently supporting ARM64 so this issue is currently moot.

**Comment by RussianNeuroMancer** [comment]
I see. Just want to let you know that this issue is blocking https://github.com/shiftkey/desktop/issues/86
