### ISSUE TITLE
port JS scripts to TS

### ISSUE THREAD

**Issue by shiftkey** [desktop/dugite-native#149]
Following on from #148, we should:

 - update the `tsconfig.json` to also compile `script/*.ts` files
 - for each `script/*.js` file, rename it to a `.ts` file
 - in the new file migrate the `@type` comments to proper type annotations
 - address any other compiler warnings
 - use atomic commits to address each migration step (rather than doing them all at once)
 - `npm install --save-dev ts-node` to run these scripts
 - update the `package.json` scripts to use `ts-node` instead of `node` and the `.ts` file in place of each `.js` file

**Comment by PaulViola** [comment]
Hello, I would like to work on this if it is still available.
