### ISSUE TITLE
add support for ARM32 packaging

### ISSUE THREAD

**Issue by andlo** [desktop/dugite-native#158]
I am building a Skill for Mycroft, that installs and set up a Theia-Ide on the device. The device is a RaspberryPi running either Raspbian jessie or Strech. But in 32 bit versions. So the precompiled package of git dosnt work on those.

Right now I just compile git and placed it manualy in place, but it would be awsome if a precompiled package for Arm32 would be made.

**Comment by shiftkey** [comment]
@andlo thanks for the interest. Our ARM64 support is a bit experimental, but we're using Docker to generate the packages so maybe we can add similar support for ARM32 in the future.

I'm going to leave this open for the moment, but I haven't figured out where to prioritize it alongside everything else...

**Comment by andlo** [comment]
Thats OK. I did find a solution, once I figured out why it didnt work ;) And I did look how you compiled the ARM64 by looking into the bildscript, so I figured out how to do the same on a 32 bit OS :)

**Comment by shiftkey** [comment]
@andlo let me know if you're interested in upstreaming the changes to add ARM32 support (or at least sharing them here for reference)

**Comment by andlo** [comment]
I would if i could…. :) 

I only looked at the compilersettings for how the Arb64 were, ad just copied it and used that for a compilation localy on my Arm32 raspberrry. So I hassnt anything to add as far as I think other than the same compitersettings works for Arm32 as for 64.
