### ISSUE TITLE
git-send-email.exe not included in Windows package

### ISSUE THREAD

**Issue by SylvainBerthelot** [desktop/dugite-native#173]
## Description

Hi, i would like to know if it's possible to not use git include in github desktop.

I explain : 

In my project i have a hook in post-commit which send me mail with the command 

> git send-email

When i commit with command line it works (commit and email) but with Github Desktop no (commit works but not email). I don't have an error or something just nothing happend except the commit.
If you ask, the hook is trigged by Github Desktop, i create text file in the hook to check that.

So i would like to know if i can change git repository used by Github Desktop or if i can add git send-email to git. 

Thanks !

## Version

* GitHub Desktop: 1.5.1

* Operating system: windows 7 professional

## Steps to Reproduce

1. Have this line in post-commit `git send-email --to some@email.com --smtp-server yourserver.com --confirm never origin/master`
2. Commit something

### Expected Behavior
Receive mail in some@email.com with last modifications.

### Actual Behavior
If i commit with 

> git commit -m "my message"

It works and i get the email.

But if i click on **Commit to master** in GithubDesktop, the commit works but i don't get the email. 

## Additional Information
I think it's because Giithub Desktop has is own git and doesn't have `git send-email` command. 

### Logs

**Log with git bash :**
 
>$ git commit -m "test"
OK. Log says:
Server: yourserver.com
MAIL FROM:<sylvain@berthelot.fr>
RCPT TO:<some@email.com>
From: Sylvain Berthelot <sylvain@berthelot.fr>
To: some@email.com
Subject: [PATCH] test
Date: Wed,  9 Jan 2019 09:47:15 +0100
Message-Id: <20190109084715.8424-1-sylvain@berthelot.fr>
X-Mailer: git-send-email 2.19.1.windows.1
MIME-Version: 1.0
Content-Transfer-Encoding: 8bit
Result: 250
[master f01ed4e] test
 2 files changed, 2 insertions(+)
 delete mode 100644 Nouveau dossier/s.txt

**Log with Github Desktop :**
>2019-01-09T15:24:47.572Z - info: [ui] Executing createCommit: git commit -F - (took 1.382s)

**Comment by SylvainBerthelot** [comment]
@shiftkey Haha okay no problem ! thx for your anwser.

**Comment by niik** [comment]
Hey @SylvainBerthelot, getting git-sendmail included into dugite-native is out of our control as it doesn't ship with the minimal distribution of Git For Windows that we use (MinGit). Should they choose to include it so will we but until that happens there's nothing for us to do here so I'm going to close the issue.

One thing you might want to try is to configure your hook script to explicitly use the Git that you've installed on your system rather than the one embedded in GitHub Desktop by updating the PATH variable and the GIT_EXEC_PATH variable.
