### ISSUE TITLE
update to Git 2.22

### ISSUE THREAD

**Issue by shiftkey** [desktop/dugite-native#264]
Git 2.22 is slated to be released June 7th, based on [the calendar](http://tinyurl.com/gitcal). The Git for Windows packages should be available a day or so after that.

**Comment by shiftkey** [comment]
The [release notes](https://github.com/git/git/blob/master/Documentation/RelNotes/2.22.0.txt) are available, to give you an idea of what's coming up.

Also, the calendar has now set Friday June 7th for the final release (currently in RC testing).

**Comment by shiftkey** [comment]
Git 2.22 was released yesterday: https://groups.google.com/forum/#!msg/git-packagers/OmNkgShbncU/YeVzReDhBgAJ

As well as Git for Windows 2.22: https://groups.google.com/forum/#!msg/git-packagers/sp5EzEQWnZY/0r2qjD8YBwAJ

And it got a shout out on the GitHub blog: https://github.blog/2019-06-07-highlights-from-git-2-22/

**Comment by niik** [comment]
Superseded by #303
