### ISSUE TITLE
Move to GitHub Actions

### ISSUE THREAD

**Issue by dennisameling** [desktop/dugite-native#337]
Travis-ci.org is shutting down on December 31st, so the build pipeline needs to be moved either to GitHub Actions to travis-ci.com (I assume you prefer the first option).

OK if I provide a PR for this? Appreciate the work you folks are doing with GH Desktop, happy to contribute back a bit this way. 😊

**Comment by niik** [comment]
Oh wow, thanks for the heads up @dennisameling! During the last release of Desktop I looked into this but only made it so far as to convert https://github.com/desktop/dugite to actions: https://github.com/desktop/dugite/pull/415 and only had time to get started on dugite-native before I was pulled in another direction.

We'd be super grateful for a PR to convert dugite-native to use actions :heart:

I just pushed the branch I started a few weeks back and cleaned it up just a little: https://github.com/desktop/dugite-native/tree/actions

Beware that it's very much a work in progress thing but If there are things from that branch you can use to get started a little faster that's great and if not then we can just toss it.

One of the main pieces that I didn't have time to look into was finding a suitable replacement for the [automatic deploy to GH Releases that travis provides](https://github.com/desktop/dugite-native/blob/3d0217c8f8ec208ef93c7bc731487a241ba7333e/.travis.yml#L63-L75). There are a few actions out there that do similar things but from my brief reconnaissance it seemed they either only support a single asset or there was some other problems with them not reusing existing releases if they exists.

Uploading assets to releases is currently done automatically when we create a tag so we'll need something similar.
