### ISSUE TITLE
Please update to latest git version to enable authenticated proxy support with LFS

### ISSUE THREAD

**Issue by mungojam** [desktop/dugite-native#355]
I've found that a very recent version of git is required for automatic authenticated proxy support on windows when pushing LFS files. It certainly works with 2.31.1.windows.1.

It does not work with the version bundled by GitHub Desktop and the limiting factor seems to be this library.

Please could you roll out an updated version and flow it through to GitHub Desktop

**Comment by mungojam** [comment]
After a bit more testing, I'm no longer convinced that it is due to the version of git. All I know is that it works fine from the command prompt, but not in GitHub desktop:

> LFS: Put "https://github-cloud.s3.amazonaws.com/alambic/media/......": Proxy authentication required

**Comment by sergiou87** [comment]
Hi @mungojam! 👋 

Thanks for your report, I'm sorry you're having issues with GitHub Desktop 😢 

As a general rule, we try to stay behind the latest releases of anything we depend on, to reduce the risk of hitting unknown bugs.

Could you explain a bit what's your setup and provide logs when the error happens? I know Desktop supports proxied connections for regular git operations, but I don't know if anything else is required specifically for LFS.

**Comment by mungojam** [comment]
> As a general rule, we try to stay behind the latest releases of anything we depend on, to reduce the risk of hitting unknown bugs.

Thanks @sergiou87, I totally understand that and I suspect now that it wouldn't help. This bug should probably live in the main GitHub Desktop repo.

Here is a bit more of the developer logs from just before the error:

> Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 2.777s)
> install.ts:31 Executing push: git -c credential.helper= -c protocol.version=2 push origin main:main --progress (took 50.353s)
> install.ts:23 `git -c credential.helper= -c protocol.version=2 push origin main:main --progress` exited with an unexpected code: 1.
> stderr:
> LFS: Put "https://github-cloud.s3.amazonaws.com/alambic/media/**redacted-ids**": Proxy authentication required

**Comment by mungojam** [comment]
We use a different proxy now so I'm unlikely to replicate this again and it never seemed to be this library anyway so I'll close this
