### ISSUE TITLE
Linux git bundle is too big

### ISSUE THREAD

**Issue by gengjiawen** [desktop/dugite-native#47]
Is there anyway we can shrink it. From the https://github.com/gengjiawen/desktop/releases release we can see the linux distro is very big. And it's caused by dugite. Is there anything we can do to optimize this?

**Comment by shiftkey** [comment]
To be honest, I've not really had a chance to analyze this. [Here's the archive contents](https://gist.github.com/shiftkey/efc528c78d7880fd8a5ce03777f38cee) - there's probably some unnecessary tools in there like `git-cvsserver` that can be removed before archiving to trim things.

There's probably also some scripting changes we could make [here](https://github.com/desktop/dugite-native/blob/master/script/build-ubuntu.sh) if you know GCC better than I do.

**Comment by shiftkey** [comment]
I've also made some changed in #48 to support iterating on the packaging steps, so someone could make changes in `script/build-ubuntu.sh` and then run `test/ubuntu.sh` to see the results of compiling and packaging, without having to push changes to a PR.

**Comment by gengjiawen** [comment]
After I do not copy static git, it looks like it became much smaller, https://github.com/gengjiawen/desktop/releases.
