### ISSUE TITLE
32-bit Windows support

### ISSUE THREAD

**Issue by shiftkey** [desktop/dugite-native#86]
There's some requests for Desktop to support 32-bit Windows https://github.com/desktop/desktop/issues/1214 and without a 32-bit Git this isn't technically possible.

Someone who wants to see this supported needs to:

 - add an entry to [`.travis.yml`](https://github.com/desktop/dugite-native/blob/master/.travis.yml) so that TravisCI will build the Windows platform using the 32-bit Git for Windows release and 32-bit Git LFS release. You can see the Git for Windows releases [here](https://github.com/git-for-windows/git/releases) and the Git LFS releases [here](https://github.com/git-lfs/git-lfs/releases). Ensure you also use the right checksums, as the build will fail if it doesn't get the bits it expects.

You can use the 64-bit Windows config as a starting point:

https://github.com/desktop/dugite-native/blob/7403fd7cb0a5aff62c4eeda1566bb897dcc4a63b/.travis.yml#L22-L29

 - [this script](https://github.com/desktop/dugite-native/blob/master/script/build-win32.sh) doesn't differentiate between 32-bit or 64-bit Windows, and it has some hard-coded `mingw64` paths that don't exist in the 32-bit version of Git for Windows - I recommend using an environment variable like `ARCH=32` or `ARCH=64` to differentiate the desired architecutre.

 - update the 64-bit Windows configuration so that it uses a `ARCH=64` environment variable

**Comment by Learning191** [comment]
I think he has been reborn in post ....hopefully. :D

**Comment by MehdiAria** [comment]
Still no news from 32 bit?

**Comment by marwasimohamed** [comment]
could anyone find a solution to this issue???

**Comment by reinajose16** [comment]
I need a 32 bit client too!

**Comment by Learning191** [comment]
yeahh !!

**Comment by baljeetsingh-mefgi** [comment]
32bit Git - Yeah Indeed.

**Comment by tapastest** [comment]
i don't know why and wht are the reason... there are people form start-up and they don't afford 64bit pc or mac....

**Comment by shiftkey** [comment]
I've updated the issue description with what needs to be updated, if someone wants to help out with contributing this.

**Comment by zetef** [comment]
just going to wait... until then I am using the web version! good luck on this issue!

**Comment by MagicMarvMan** [comment]
I am working on a solution #93

**Comment by j-f1** [comment]
Time to unlock & reopen the desktop/desktop issue?

**Comment by shiftkey** [comment]
> Time to unlock & reopen the desktop/desktop issue?

Not quite yet:

 - needs a release (underway) 
 - needs to update `dugite` to install the 32-bit native package if running on `win32` and `x86`
 - need to publish an update to `dugite` to NPM
 - needs to update `dugite` in Desktop and test Git 2.18.0 properly for current platforms

Then we need to look at how we handle non-x64 platforms in our toolchain:

 - we had to do [this sort of workaround](https://github.com/desktop/desktop/blob/master/script/install-arm64-deps.sh) for ARM64 support just to get things building
 - we probably to make some changes to how things are built, tested and packaged
 - then we need to look at distributing bits, which requires touching infrastructure and updates and all other fun stuff

I'll open a fresh issue once the Git tooling is in a state that we can re-evaluate that.

**Comment by MatheusGonzaga2000** [comment]
Sou usuário 32 bits do Windows e estou me juntando a discussão para que o 32 bits Git para sistemas operacionais do Windows 32 Bits, possa ser providenciando.

Infelizmente estou realizando cursos que possam complementar a minha grade da Universidade e me vejo em um impasse crucial de continuar seguindo em frente sem conseguir trabalhar com essa tecnologia.

No momento não me vejo na possibilidade de realizar um update para 64bits, apesar dos gráficos apontarem para 720mil/24milh, acredito que muitos estão sendo prejudicados e que uma solução para que possa fornecer apoio a esses usuários, possa ser pensada.

**Comment by danh23072004** [comment]
Just waiting for 32bit version ...

**Comment by uzervlad** [comment]
One and a half year, still waiting

**Comment by SultanMu** [comment]
got my new ARM based surface pro x with NVIDIA gpus - may have to return it if can't install GitHub desktop. A 32bit version is badly needed.

**Comment by KisaragiEffective** [comment]
> One and a half year, still waiting

and another half year was past...

**Comment by theAlphaBeth** [comment]
Ouch, still waiting.

**Comment by Myst1ka** [comment]
Im waiting too, i really need it :)

**Comment by spattanaik01** [comment]
Need 32-bit github desktop :)

**Comment by FrancescoRapisarda** [comment]
anchi'io stesso problema. Spero nel lancio della versione desktop 32 bit.
